### ISSUE TITLE
 Error: SQLITE_ERROR: no such table: settings

### ISSUE THREAD

**Issue by abuzaforbg** [thetutlage/ghost-sitemap#1]
I've installed Ghost Sitemap generator to my ghost installation, But Unfortunately I can't generate sitemap file.

When I am running <code>ghostSitemap generate</code> command, The output is:

<code>/var/www/ghost# ghostSitemap generate
Started creating sitemap.....
Fetching posts ....
✖ Error: SQLITE_ERROR: no such table: settings</code>

**Comment by thetutlage** [comment]
Which version of ghost you running and also change environment in your sitemapfile.json to production ( if you are running it on production )

**Comment by thetutlage** [comment]
Closing
